// Typescript bindings for cuon-matrix-cse160.js and cuon-utils.js
// Generated by Claude Sonnet 4.5

declare class Vector3 {
    elements: Float32Array;
    constructor(opt_src?: number[] | Float32Array);
    set(src: Vector3): this;
    add(other: Vector3): this;
    sub(other: Vector3): this;
    div(scalar: number): this;
    mul(scalar: number): this;
    static dot(other1: Vector3, other2: Vector3): number;
    static cross(other1: Vector3, other2: Vector3): Vector3;
    mag(): number;
    normalize(): this;
}

declare class Vector4 {
    elements: Float32Array;
    constructor(opt_src?: number[] | Float32Array);
}

declare class Matrix4 {
    elements: Float32Array;
    constructor(opt_src?: Matrix4 | number[]);
    
    setIdentity(): this;
    set(src: Matrix4): this;
    copy(src: Matrix4): this;
    concat(other: Matrix4): this;
    multiply(other: Matrix4): this;
    multiplyVector3(pos: Vector3): Vector3;
    multiplyVector4(pos: Vector4): Vector4;
    transpose(): this;
    setInverseOf(other: Matrix4): this;
    invert(): this;
    
    setOrtho(left: number, right: number, bottom: number, top: number, near: number, far: number): this;
    ortho(left: number, right: number, bottom: number, top: number, near: number, far: number): this;
    setFrustum(left: number, right: number, bottom: number, top: number, near: number, far: number): this;
    frustum(left: number, right: number, bottom: number, top: number, near: number, far: number): this;
    setPerspective(fovy: number, aspect: number, near: number, far: number): this;
    perspective(fovy: number, aspect: number, near: number, far: number): this;
    
    setScale(x: number, y: number, z: number): this;
    scale(x: number, y: number, z: number): this;
    setTranslate(x: number, y: number, z: number): this;
    translate(x: number, y: number, z: number): this;
    setRotate(angle: number, x: number, y: number, z: number): this;
    rotate(angle: number, x: number, y: number, z: number): this;
    
    setLookAt(
        eyeX: number, eyeY: number, eyeZ: number,
        centerX: number, centerY: number, centerZ: number,
        upX: number, upY: number, upZ: number
    ): this;
    lookAt(
        eyeX: number, eyeY: number, eyeZ: number,
        centerX: number, centerY: number, centerZ: number,
        upX: number, upY: number, upZ: number
    ): this;
    
    dropShadow(plane: number[], light: number[]): this;
    dropShadowDirectionally(normX: number, normY: number, normZ: number, planeX: number, planeY: number, planeZ: number, lightX: number, lightY: number, lightZ: number): this;
}

declare function initShaders(
    gl: WebGLRenderingContext,
    vshader: string,
    fshader: string
): boolean;

declare function createProgram(
    gl: WebGLRenderingContext,
    vshader: string,
    fshader: string
): WebGLProgram | null;

declare function loadShader(
    gl: WebGLRenderingContext,
    type: number,
    source: string
): WebGLShader | null;

declare function getWebGLContext(
    canvas: HTMLCanvasElement,
    opt_debug?: boolean
): WebGLRenderingContext | null;

// Extend WebGLRenderingContext to include program property
interface WebGLRenderingContext {
    program?: WebGLProgram;
}

// Extend Window interface for global variables
interface Window {
    GL: WebGLRenderingContext;
    a_Position: number;
    a_Normal: number;
    u_FragColor: WebGLUniformLocation;
    u_ModelMatrix: WebGLUniformLocation;
    u_GlobalRotation: WebGLUniformLocation;
    u_ProjectionMatrix: WebGLUniformLocation;
}
