// TypeScript bindings for animation.js
// Provides type definitions for animation system used in assignments
// Generated by Claude Sonnet 4.5

// Type definitions for animation system
interface TransformData {
    rotation?: [number, number, number];
}

interface Keyframe {
    time: number;
    transforms: Record<string, TransformData>;
}

interface Animation {
    duration: number;
    keyframes: Keyframe[];
    loop?: boolean;
    seamlessLoop?: boolean;
    disallowInterrupt?: boolean;
}

interface Rig {
    [boneName: string]: {
        rotation: [number, number, number];
        setPos: (x: number, y: number, z: number) => void;
        setScale: (x: number, y: number, z: number) => void;
        setRot: (pitch: number, yaw: number, roll: number) => void;
    };
}

declare class AnimMan {
    constructor(rig: Rig, animations: Record<string, Animation>);
    
    setUserRotation(boneName: string, rotation: [number, number, number]): void;
    clearUserRotation(boneName: string): void;
    
    update(dt: number): void;
    
    queueAnim(key: string): void;
    interruptAnimQueue(key: string): void;
    clearQueue(): void;
    
    getActiveAnimation(): string | null;
    isPlaying(key: string): boolean;
    getQueueLength(): number;
    getQueueInfo(): string[];
}

export { AnimMan, TransformData, Keyframe, Animation, Rig };
