// TypeScript bindings for camera.js
// Provides type definitions for Camera class used in assignments
// Generated by Claude Sonnet 4.5

import Transform from './transform.js';

export const CameraMode: {
    readonly TRACK: 0;
    readonly FREE: 1;
    readonly ORBIT: 2;
};

export type CameraModeType = typeof CameraMode[keyof typeof CameraMode];

declare class Camera {
    transform: Transform | null;
    target: Transform | null;
    
    mode: CameraModeType;
    distance: number;
    moveSpeed: number;
    
    isDragging: boolean;
    lastMouseX: number;
    lastMouseY: number;
    invertX: boolean;
    invertY: boolean;
    
    keyStates: Record<string, boolean>;
    
    constructor(
        transform?: Transform | null,
        target?: Transform | null,
        mode?: CameraModeType
    );
    
    /**
     * Update camera position and orientation based on mode and input
     * @param dt - Delta time in seconds
     */
    update(dt: number): void;
    
    /**
     * Get the view matrix for rendering
     */
    getViewMatrix(): Matrix4;
    
    /**
     * Handle mouse drag for camera rotation
     * @param deltaX - Mouse movement in X
     * @param deltaY - Mouse movement in Y
     */
    handleMouseDrag(deltaX: number, deltaY: number): void;
    
    /**
     * Handle mouse wheel for distance/speed adjustment
     * @param delta - Wheel delta
     * @param maxSpeed - Maximum movement speed (default: 0.1)
     * @param step - Speed adjustment step (default: 0.001)
     */
    handleMouseWheel(delta: number, maxSpeed?: number, step?: number): void;
    
    /**
     * Transition between camera modes
     * @param newMode - New camera mode
     */
    setMode(newMode: CameraModeType): void;
    
    // Private helper methods
    _getAngles(): [number, number];
    _getMovementVectors(angleY: number): {
        forwardX: number;
        forwardZ: number;
        rightX: number;
        rightZ: number;
    };
    _getTrackingVectors(targetX: number, targetZ: number, camX: number, camZ: number): {
        forwardX: number;
        forwardZ: number;
        rightX: number;
        rightZ: number;
    };
    _getOrbitPosition(targetX: number, targetY: number, targetZ: number, distance: number, angleX: number, angleY: number): {
        x: number;
        y: number;
        z: number;
    };
    _getLookAtPoint(angleX: number, angleY: number, distance?: number): {
        x: number;
        y: number;
        z: number;
    };
    _anglesToDir(ax: number, ay: number): [number, number, number];
    _dirToAngles(dx: number, dy: number, dz: number): [number, number] | null;
}

export default Camera;
