// TypeScript bindings for camera.js
// Provides type definitions for Camera class used in assignments
// Generated by Claude Sonnet 4.5

import Transform from './transform.js';

export const CameraMode: {
    readonly TRACK: 0;
    readonly FREE: 1;
    readonly ORBIT: 2;
};

export type CameraModeType = typeof CameraMode[keyof typeof CameraMode];

declare class Camera {
    transform: Transform | null;
    target: Transform | null;
    
    mode: CameraModeType;
    distance: number;
    moveSpeed: number;
    
    angleX: number;  // Pitch in degrees
    angleY: number;  // Yaw in degrees
    
    isDragging: boolean;
    lastMouseX: number;
    lastMouseY: number;
    invertX: boolean;
    invertY: boolean;
    
    keyStates: Record<string, boolean>;
    
    constructor(
        transform?: Transform | null,
        target?: Transform | null,
        mode?: CameraModeType
    );
    
    /**
     * Update camera position and orientation based on mode and input
     * @param dt - Delta time in seconds
     */
    update(dt: number): void;
    
    /**
     * Get the view matrix for rendering
     */
    getViewMatrix(): Matrix4;
    
    /**
     * Handle mouse drag for camera rotation
     * @param deltaX - Mouse movement in X
     * @param deltaY - Mouse movement in Y
     */
    handleMouseDrag(deltaX: number, deltaY: number): void;
    
    /**
     * Handle mouse wheel for distance/speed adjustment
     * @param delta - Wheel delta
     * @param maxSpeed - Maximum movement speed
     * @param step - Speed adjustment step
     */
    handleMouseWheel(delta: number, maxSpeed?: number, step?: number): void;
    
    /**
     * Transition between camera modes
     * @param newMode - New camera mode
     */
    setMode(newMode: CameraModeType): void;
}

export default Camera;
