// TypeScript bindings for shapes.js
// Provides type definitions for Shape classes used in assignments
// Generated by Claude Sonnet 4.5

import Transform from './transform';

declare class Shape {
    static vBuffer: WebGLBuffer | null;
    static vertexData: number[];
    static vertexCount: number;
    static vertexOffset: number;
    
    static nBuffer: WebGLBuffer | null;
    static normalData: number[];
    
    transform: Transform;
    colour: [number, number, number, number];
    
    static initSharedBuffer(): void;
    
    constructor(transform: Transform, colour: [number, number, number, number]);
    
    setColour(): void;
    render(): void;
}

declare class Cube extends Shape {
    static vertexCount: number;
    static vertexOffset: number;
}

declare class SlantedCube extends Cube {
    static vertexOffset: number;
}

declare class Ramp extends Cube {
    static vertexOffset: number;
}

declare class Cylinder extends Shape {
    static vertexCount: number;
    static vertexOffset: number;
}

declare class Cylinder16 extends Cylinder {
    static vertexCount: number;
    static vertexOffset: number;
}

export default Shape;
export { Cube, SlantedCube, Ramp, Cylinder, Cylinder16 };
