// TypeScript bindings for shapes.js
// Provides type definitions for Shape classes used in assignments
// Generated by Claude Sonnet 4.5

import Transform from './transform.js';

export interface MaterialProperties {
    shininess?: number;
    specularStrength?: number;
    rimStrength?: number;
    UVScale?: [number, number];
}

export interface GLStateOverrides {
    cullFace?: boolean | null;
    cullFaceMode?: number | null;
    depthTest?: boolean | null;
    depthMask?: boolean | null;
    blend?: boolean | null;
    blendSrc?: number | null;
    blendDst?: number | null;
}

declare class Shape {
    // ─── Static geometry buffers ──────────────────────────────────────
    static vBuffer: WebGLBuffer | null;
    static vertexData: number[] | null;
    static vertexCount: number;
    static vertexOffset: number;
    static nBuffer: WebGLBuffer | null;
    static normalData: number[] | null;
    static uvBuffer: WebGLBuffer | null;
    static uvData: number[] | null;
    
    // ─── Static GL state ──────────────────────────────────────────────
    static glState: {
        cullFace: boolean;
        cullFaceMode: number;
        depthTest: boolean;
        depthMask: boolean;
        blend: boolean;
        blendSrc: number;
        blendDst: number;
    } | null;
    
    static initSharedBuffer(): void;
    
    // ─── Instance properties ──────────────────────────────────────────
    transform: Transform;
    tint: [number, number, number, number];
    texturePath: string;
    texturePromise: Promise<void>;
    alphaCutout: number;
    
    glStateOverrides: GLStateOverrides;
    
    shininess: number;
    specularStrength: number;
    rimStrength: number;
    UVScale: [number, number];
    
    isClone?: boolean;
    
    // Optional instance overrides (used by Mesh)
    vBuffer?: WebGLBuffer | null;
    nBuffer?: WebGLBuffer | null;
    uvBuffer?: WebGLBuffer | null;
    vertexCount?: number;
    vertexOffset?: number;
    
    constructor(
        transform?: Transform | null,
        tint?: [number, number, number, number],
        clipAlpha?: number,
        texturePath?: string | null,
        material?: MaterialProperties | null
    );
    
    setTint(): void;
    setMaterial(props?: MaterialProperties | null): this;
    loadTexture(path: string): Promise<void>;
    isPowerOf2(value: number): boolean;
    render(): void;
    setGLState(overrides: Partial<GLStateOverrides>): this;
    clone(transform?: Transform | null, colour?: [number, number, number, number] | null): Shape;
    destroy(): void;
    
    // Private methods
    _applyGLState(): Record<string, any>;
    _restoreGLState(prevState: Record<string, any>): void;
}

export declare class Plane extends Shape {
    static vertexData: number[];
    static vertexCount: 6;
    static vertexOffset: number;
    static normalData: number[];
    static uvData: number[];
}

export declare class Cube extends Shape {
    static vertexData: number[];
    static vertexCount: 36;
    static vertexOffset: number;
    static normalData: number[];
    static uvData: number[];
}

export declare class SlantedCube extends Cube {
    static vertexOffset: number;
}

export declare class Ramp extends Cube {
    static vertexOffset: number;
}

export declare class Cylinder extends Shape {
    static vertexData: number[];
    static vertexCount: number;
    static vertexOffset: number;
    static normalData: number[];
    static uvData: number[];
}

export declare class Cylinder16 extends Cylinder {
    static vertexCount: number;
    static vertexOffset: number;
}

export declare class Mesh extends Shape {
    static initSharedBuffer(): void;
    
    constructor(
        transform: Transform | null,
        colour: [number, number, number, number],
        clipAlpha: number,
        vertexData: Float32Array | number[],
        normalData: Float32Array | number[],
        uvData?: Float32Array | number[] | null,
        texturePath?: string | null
    );
}

export declare class TextureCache {
    private cache: Map<string, { texture: WebGLTexture; promise: Promise<WebGLTexture> }>;
    
    constructor();
    
    /**
     * Load a texture from path, or return cached version if already loaded
     * @param path - Path to image file
     * @returns Promise that resolves to WebGL texture
     */
    load(path: string): Promise<WebGLTexture>;

    /**
     * Get a cached texture synchronously
     * @param path - Path to image file
     * @returns Texture if cached, null otherwise
     */
    get(path: string): WebGLTexture | null;
	isLoaded(path: string): boolean;
    
    isPowerOf2(value: number): boolean;
}

export const TEXTURE_CACHE: TextureCache;
export default Shape;
