// TypeScript bindings for transform.js
// Provides type definitions for Transform class used in assignments
// Generated by Claude Sonnet 4.5

declare class Transform {
    position: [number, number, number];
    rotation: [number, number, number];  // degrees, XYZ
    scale: [number, number, number];
    parent: Transform | null;
    children: Transform[];
    
    localMatrix: Matrix4;
    worldMatrix: Matrix4;
    
    constructor(
        pos?: [number, number, number],
        rotation?: [number, number, number],
        scale?: [number, number, number],
        parent?: Transform | null
    );
    
    setPos(x: number, y: number, z: number): this;
    setRot(rx: number, ry: number, rz: number): this;
    setScale(sx: number, sy: number, sz: number): this;
    translate(x: number, y: number, z: number): this;
    
    recomputeCache(): void;
    
    addChild(child: Transform): this;
    removeChild(child: Transform): this;
    setParent(parent: Transform | null): this;
    
    getWorldPosition(): [number, number, number];
    getWorldRotation(): [number, number, number];
    
    clone(): Transform;
    
    static getHierarchyGraph(rootTransform: Transform): {
        nodes: Array<{ transform: Transform; position: [number, number, number] }>;
        edges: Array<{
            from: [number, number, number];
            to: [number, number, number];
            parent: Transform;
            child: Transform;
        }>;
    };
}

export default Transform;
